config/routes.rb
Rails.application.routes.draw do

  resources :exercises
  resources :foods
  devise_for :users, :controllers => { registrations: 'registrations' }

  root "pages#show", page: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  validates_presence_of :description, :activity, :calories, :date
  belongs_to :user
end

app/models/food.rb
class Food < ActiveRecord::Base
  validates_presence_of :description, :meal, :calories, :date
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :exercises
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    exercises_path
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :find_exercise, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @exercises = Exercise.all
    @foods = Food.all
  end

  def new
    @exercise = current_user.exercises.build
  end

  def create
    @exercise = current_user.exercises.build(exercise_params)
    respond_to do |format|
      if @exercise.save(exercise_params)
        format.html { exercises_path }
        format.js
      else
        format.html { render :new }
        format.js { render :errors }
      end
    end
  end

  def show

  end

  private
  def exercise_params
    params.require(:exercise).permit(:description, :activity, :calories, :date)
  end

  def find_exercise
    @exercise = Exercise.find(params[:id])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @foods = Food.all
  end

  def new
    @food = current_user.foods.build
  end

  def create
    @food = current_user.foods.build(food_params)
    respond_to do |format|
      if @food.save(food_params)
        format.html { redirect_to exercises_path }
        format.js
      else
        format.html { render :new }
        format.js { render :errors }
      end
    end
  end

  def show

  end

  private
  def food_params
    params.require(:food).permit(:description, :meal, :calories, :date)
  end

  def find_food
    @food = Food.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end  

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:height, :user_name, :dob, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:height, :user_name, :dob, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercises/_exercise.html.erb
    <li><%= link_to exercise.description, exercise_path(exercise) %> | <%= exercise.activity %> | <%= exercise.calories %> | <%= exercise.date %> </li>

app/views/exercises/_food.html.erb
<li><%= link_to food.description, food_path(food) %> | <%= food.meal %> | <%= food.calories %> | <%= food.date %> </li>

app/views/exercises/_form.html.erb
<%= form_for @exercise, remote: true do |f| %>
<%= render "layouts/errors", :object => @exercise %>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :activity %>
  <%= f.text_field :activity %><br>
  <%= f.label :calories %>
  <%= f.text_field :calories %><br>
  <%= f.label :date %>
  <%= f.date_field :date %><br>
  <%= f.submit %>
<% end %>

app/views/exercises/create.js.erb
$('#errors').remove();
$('#new_exercise').hide();
$('#new_exercise_link').show();
$('#exercise_list').append('<%= j render(@exercise) %>');

app/views/exercises/errors.js.erb
$('#errors').remove();
$('#new_exercise').before('<%= j render("layouts/errors", :object => @exercise)%>');

app/views/exercises/index.html.erb
<h2 id="center">Home Page</h2>
<div class="row">
  <div class="col-sm-6">
    <h3>Exercise</h3>
    <ul id="exercise_list">
      <% @exercises.each do |exercise| %>
        <%= render "exercise", :exercise => exercise %>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-6">
    <h3>Food</h3>
    <ul id="food_list">
      <% @foods.each do |food| %>
        <%= render "food", :food => food %>
      <% end %>
    </ul>
  </div>
</div>
<hr>

<%= link_to "New Exercise", new_exercise_path, remote: true, id: "new_exercise_link" %><br>
<%= link_to "New Food", new_food_path, remote: true, id: "new_food_link" %>

app/views/exercises/new.js.erb
$('#new_exercise_link').hide().after("<%= j render('form') %>")

app/views/exercises/show.html.erb
<h2>home page for singular exercise</h2>

<%= @exercise.description %>

app/views/foods/_food.html.erb
    <li><%= link_to food.description, food_path(food) %> | <%= food.meal %> | <%= food.calories %> | <%= food.date %> </li>

app/views/foods/_form.html.erb
<%= form_for @food, remote: true do |f| %>
<%= render "layouts/errors", :object => @food %>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.select :meal, [['Breakfast','breakfast'],['Lunch','lunch'],['Dinner','dinner']] %><br>
  <%= f.label :calories %>
  <%= f.text_field :calories %><br>
  <%= f.label :date %>
  <%= f.date_field :date %><br>
  <%= f.submit %>
<% end %>

app/views/foods/create.js.erb
$('#errors').remove();
$('#new_food').hide();
$('#new_food_link').show();
$('#food_list').append('<%= j render(@food) %>');

app/views/foods/errors.js.erb
$('#errors').remove();
$('#new_food').before('<%= j render("layouts/errors", :object => @food)%>');

app/views/foods/index.html.erb
<h2>home page for food</h2>

<ul>
  <% @foods.each do |food| %>
    <%= render "food", :food => food %>
  <% end %>
</ul>

<hr>

<%= link_to "New Food", new_food_path %>

app/views/foods/new.html.erb
<%= render 'form'%>

app/views/foods/new.js.erb
$('#new_food_link').hide().after("<%= j render('form') %>")

app/views/foods/show.html.erb
<h2>home page for singular food</h2>

<%= @food.description %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div id="errors">
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostIt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <h2>Home Page</h2>

  <p>This would be a static home page in a Rails application.</p>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %><br>
  <%= link_to "Account", edit_user_registration_path %><br>
  <%= link_to "Sign Up", new_user_registration_path %><br>
  <%= link_to "Sign In", new_user_session_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>